package com.hugelist.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;



/**
 * ItemType generated by hbm2java
 */

/*
 CREATE TABLE itemtype (
  itemtypeid text,
  name text,
  PRIMARY KEY (itemtypeid)
);
 */

@Entity
@Table(name = "itemtype", schema = "hugelist@cassandra_hugelist")
public class ItemType implements java.io.Serializable {
	
	private static final long serialVersionUID = 3L;
	
	@Id
	@Column(name = "itemtypeid")
	private String id;
	

	@Column(name = "name")
	private String name;

	public ItemType() {
	}
	
	public ItemType(String id) {
		this.id = id;
	}

	public ItemType(String id, String name) {
		this.id = id;
		this.name = name;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
