package com.hugelist.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ClassItem generated by hbm2java
 */
/*
 * CREATE TABLE classitem ( classitemid text, classificationrefid text,
 * classitemname text, itemtyperefid text, valueunit text, PRIMARY KEY
 * (classitemid) );
 */

@Entity
@Table(name = "classitem", schema = "hugelist@cassandra_hugelist")
public class ClassItem implements java.io.Serializable {
	private static final long serialVersionUID = 3L;

	@Id
	@Column(name = "classitemid")
	private String id;

	@Column(name = "classitemname")
	private String name;

	@Column(name = "valueunit")
	private String valueUnit;

	@Column(name = "itemtyperefid")
	private String itemTypeId;

//	@ManyToOne(fetch = FetchType.LAZY)
//	@JoinColumn(name = "classificationid")
//	private Classification classification;

//	public Classification getClassification() {
//		return classification;
//	}
//
//	public void setClassification(Classification classification) {
//		this.classification = classification;
//	}

	public ClassItem() {
	}

	public ClassItem(String id, String name, String valueUnit, String itemTypeId) {
		super();
		this.id = id;
		this.name = name;
		this.valueUnit = valueUnit;
		this.itemTypeId = itemTypeId;
	}

	public String getItemTypeId() {
		return this.itemTypeId;
	}

	public void setItemTypeId(String itemTypeId) {
		this.itemTypeId = itemTypeId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getValueUnit() {
		return this.valueUnit;
	}

	public void setValueUnit(String valueUnit) {
		this.valueUnit = valueUnit;
	}
}
